Prevedel vse v angleščino.
k3ap/prog2-go pull request #7
Opened 2023-04-24 06:21 UTC by jakavel

Prevedel vsa imena razredov spremenljivk in metod ter vse komentarje v Angleščino.

2023-04-24 06:46 UTC, k3ap requested changes
Preberi [](https://ucilnica.fmf.uni-lj.si/mod/page/view.php?id=58200)

2023-04-24 06:46 UTC, k3ap commented on src/intelligence/Intelligence.java
Ime paketa in razreda morata nujno biti v slovenščini.
Prav tako mora biti metoda `izberiPotezo` v slovenščini.

2023-04-24 06:46 UTC, k3ap commented on src/logika/BreadthSearch.java
BreadthFirstSearch

2023-04-24 06:46 UTC, k3ap commented on src/logika/BreadthSearch.java
> +	private LinkedList<Index> indexToSearch;
`indiciesToSearch`

2023-04-24 06:46 UTC, k3ap commented on src/logika/BreadthSearch.java
> +	protected void beginning(Index zacetniIdx) {
`start` ali `startAtIndex` je bolje.
`zacetniIdx` ni preveden

2023-04-24 06:46 UTC, k3ap commented on src/logika/BreadthSearch.java
> +	protected boolean isNext() {
`hasNext`

2023-04-24 06:46 UTC, k3ap commented on src/logika/DepthSearch.java
DepthFirstSearch

Sicer pa enaki komentarji kot pri BFS

2023-04-24 06:46 UTC, k3ap commented on src/logika/FieldColor.java
> +	EMPTY, BLACKFIELD, WHITEFIELD;
Jaz bi imel raje samo `BLACK`, `WHITE`

2023-04-24 06:46 UTC, k3ap commented on src/logika/Game.java
Ime razreda ter metoda `odigraj` morata biti nujno v slovenščini

2023-04-24 06:46 UTC, k3ap commented on src/logika/Game.java
> +	 * Who's turn is it.
A ni _whose_ bolje?

2023-04-24 06:46 UTC, k3ap commented on src/logika/Grid.java
> +	 * Holds the "color" of the vertices; vertices at the same color, when they are in the same component
_have_ the same color

2023-04-24 06:46 UTC, k3ap commented on src/logika/Grid.java
> +	private class LipertiesSearchData extends SearchData {
typo

2023-04-24 06:46 UTC, k3ap commented on src/logika/Grid.java
> +	 * This array is filled out by ComponentSearch.
_filled out_ je čuden izraz, bolje samo _filled_

2023-04-24 06:46 UTC, k3ap commented on src/intelligence/Intelligence.java
Razred in `izberiPotezo` morata biti nujno v slovenščini

2023-04-24 06:46 UTC, k3ap commented on src/logika/Igra.java
Igra mora biti nujno v slovenščini.

2023-04-24 06:46 UTC, k3ap commented on src/logika/Index.java
> + * Entirely equivalent to the `Poteza` class but it's separated due to semantic reasons.
_for semantic reasons_

2023-04-24 06:46 UTC, k3ap commented on src/logika/Search.java
> +	protected abstract void beginning(Index startIdx);
Bolje `start` ali `startAt`

2023-04-24 06:46 UTC, k3ap commented on src/logika/Search.java
> +	protected abstract boolean isNext();
Bolje `hasNext`

2023-04-24 06:46 UTC, k3ap commented on src/logika/Search.java
> +	protected boolean addNeighbor(Index parent, Index neighbor) {
Ali bi bilo bolje pisati v angleški angleščini?

2023-04-24 06:46 UTC, k3ap commented on src/logika/Search.java
> +	 * Function that takes a step in the direction of the search.
_that makes a search step_

Iskanje nima zares smeri.

2023-04-24 06:46 UTC, k3ap commented on src/logika/SearchData.java
> +	public boolean toSearch(Index idx) {
`hasSearched` je bolj deskriptivno

2023-04-24 06:46 UTC, k3ap commented on src/logika/SearchData.java
> +	public void simplify() {
`clear` ali `reset`

2023-04-24 06:46 UTC, k3ap commented on src/vodja/ManagedGame.java
> +	private void dealWithType(GameType gameType) {
To se mi zdi malo žaljivo ime, kakor da imaš jake probleme s tipom

2023-04-24 07:48 UTC, k3ap requested changes

2023-04-24 07:48 UTC, k3ap commented on src/inteligenca/MooveChooser.java
typo

2023-04-24 07:48 UTC, k3ap commented on src/inteligenca/MooveChooser.java
typo

2023-04-24 07:48 UTC, k3ap commented on src/inteligenca/RandomMoveChooser.java
> +		System.out.println(idx + " od " + validMoves.size());
tale print ni potreben

2023-04-24 07:48 UTC, k3ap commented on src/logika/DepthFirstSearch.java
> + * the same as BreadthSearch except that it uses a stack instead of a queue.
BreadthFirstSearch

2023-04-24 07:48 UTC, k3ap commented on src/logika/FieldColor.java
> + * The color of a field in the grid, either EMPTY, BLACKFIELD, or WHITEFIELD.
BLACK, WHITE

2023-04-26 06:09 UTC, k3ap commented
Še vedno bi rad tiste 3 stvari od zgoraj

2023-04-26 06:33 UTC, jakavel commented on src/logika/SearchData.java
> +	public boolean toSearch(Index idx) {
Sem dal na `hasNotSearched` ker se mi zdi bolj primerno glede na delovanje metode.

2023-04-26 06:34 UTC, k3ap approved these changes

2023-04-26 06:37 UTC, merged